import {base} from "next/dist/build/webpack/config/blocks/base";


// components/RootLayout.js
import Link from 'next/link';
import React from "react";
import './globals.css'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className={''}>
            <div className="">{children}</div>
        </body>
        </html>
    );
}